In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
a = np.arange(1, 11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [4]:
zero_matrix = np.zeros((3, 3), dtype="int")
zero_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.


In [5]:
random_matrix = np.random.randint(1, 11, (5, 5))
random_matrix

array([[ 9,  8,  9,  4,  9],
       [ 8,  1,  9,  8,  9],
       [10,  5, 10,  5,  4],
       [ 3,  1,  9,  1,  3],
       [ 2,  7,  6, 10,  4]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.



In [6]:
random_matrix_0_1 = np.random.random((4, 4))
random_matrix_0_1

array([[0.68190984, 0.19662572, 0.44252762, 0.86401268],
       [0.76359457, 0.94151713, 0.57696702, 0.20552982],
       [0.75447995, 0.82441922, 0.88157399, 0.11432863],
       [0.19400229, 0.29843421, 0.61317829, 0.69805976]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.



In [7]:
first = np.random.randint(1, 11, (5,))
second = np.random.randint(1, 11, (5,))
print(f'first= {first}')
print(f'second= {second}')

print('plus=', first + second)
print('minus=', first - second)
print('multiplication=', first * second)

first= [1 5 1 5 8]
second= [8 8 2 9 3]
plus= [ 9 13  3 14 11]
minus= [-7 -3 -1 -4  5]
multiplication= [ 8 40  2 45 24]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.



In [8]:
first = np.random.random((7,))
second = np.random.random((7,))
print(np.dot(first, second))

1.57252084418269


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.



In [9]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 3))
np.dot(m1, m2)

array([[52, 88, 80],
       [19, 49, 47]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.



In [10]:
matrix = np.random.randint(1, 11, (3, 3))
np.linalg.inv(matrix)

array([[ 1. ,  3.2, -1.2],
       [ 1. ,  1.8, -0.8],
       [-2. , -5.2,  2.2]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.



In [14]:
matrix = np.random.random((4, 4))
matrix.T

array([[0.49374428, 0.55179933, 0.91782141, 0.63902028],
       [0.43810798, 0.09114714, 0.79997834, 0.96593351],
       [0.94453714, 0.69221274, 0.75941192, 0.85132319],
       [0.87975555, 0.23088242, 0.70396838, 0.95620415]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.



In [15]:
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, (4, ))
np.dot(matrix, vector)

array([145, 163, 159])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.



In [ ]:
matrix = np.random.random((3, 4))
vector = np.random.random((4, ))
np.dot(matrix, vector)

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.



In [23]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
m1 * m2

array([[50, 60],
       [21, 35]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.



In [25]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
np.dot(m1, m2)

array([[72, 14],
       [94, 18]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.



In [26]:
matrix = np.random.randint(1, 101, (5, 5))
np.sum(matrix)

1425

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.



In [27]:
m1 = np.random.randint(1, 11, (4, 4))
m2 = np.random.randint(1, 11, (4, 4))
m1 - m2

array([[ 5, -2, -3, -1],
       [-3,  0, -1,  1],
       [-1, -8,  2, -4],
       [ 3,  2,  5,  2]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.



In [30]:
matrix = np.random.rand(3, 3)
np.sum(matrix, axis=1, keepdims=True)

array([[1.65221735],
       [2.28833317],
       [0.72650746]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.



In [36]:
matrix = np.random.randint(1, 11, (3, 4))
matrix ** 2

array([[81,  1, 81, 64],
       [ 9,  9, 36,  1],
       [36,  4,  4, 49]])

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.



In [58]:
vector = np.random.randint(1, 51, (4, ))
np.sqrt(vector)

array([6.8556546 , 7.07106781, 2.82842712, 6.        ])